// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentMarketPlace.Data;

#nullable disable

namespace TalentMarketPlace.Migrations
{
    [DbContext(typeof(TalentMarketplaceDbContext))]
    partial class TalentMarketplaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIRecommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AIScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerFeedback")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MatchPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RequirementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequirementId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVectorIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastResumeUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VectorIndexedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearsOfExperience")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            AvailabilityStatus = "Available",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(480),
                            Designation = "Senior Software Engineer",
                            Email = "arun.kumar@company.com",
                            FullName = "Arun Kumar",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bangalore",
                            PhoneNumber = "9876543210",
                            TeamId = 1,
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(480),
                            UserId = 1,
                            YearsOfExperience = 5m
                        },
                        new
                        {
                            EmployeeId = 2,
                            AvailabilityStatus = "Limited",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(490),
                            Designation = "DevOps Engineer",
                            Email = "beena.singh@company.com",
                            FullName = "Beena Singh",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bangalore",
                            PhoneNumber = "9876543211",
                            TeamId = 3,
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(490),
                            UserId = 2,
                            YearsOfExperience = 4m
                        },
                        new
                        {
                            EmployeeId = 3,
                            AvailabilityStatus = "Available",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(490),
                            Designation = "Full Stack Developer",
                            Email = "rajesh.nair@company.com",
                            FullName = "Rajesh Veerasamy",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Chennai",
                            PhoneNumber = "9876543212",
                            TeamId = 1,
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(490),
                            UserId = 3,
                            YearsOfExperience = 3m
                        },
                        new
                        {
                            EmployeeId = 4,
                            AvailabilityStatus = "Available",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(490),
                            Designation = "Backend Developer",
                            Email = "priya.sharma@company.com",
                            FullName = "Priya Sharma",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2022, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bangalore",
                            PhoneNumber = "9876543213",
                            TeamId = 2,
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(490),
                            UserId = 4,
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            EmployeeId = 5,
                            AvailabilityStatus = "Not Available",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(500),
                            Designation = "Tech Lead",
                            Email = "vikram.reddy@company.com",
                            FullName = "Vikram Raja",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2016, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Chennai",
                            PhoneNumber = "9876543214",
                            TeamId = 1,
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(500),
                            UserId = 5,
                            YearsOfExperience = 8m
                        },
                        new
                        {
                            EmployeeId = 6,
                            AvailabilityStatus = "Available",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(500),
                            Designation = "HR Manager",
                            Email = "hr.manager@company.com",
                            FullName = "HR Manager",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2014, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bangalore",
                            PhoneNumber = "9876543215",
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(500),
                            UserId = 6,
                            YearsOfExperience = 10m
                        },
                        new
                        {
                            EmployeeId = 7,
                            AvailabilityStatus = "Available",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(500),
                            Designation = "Engineering Manager",
                            Email = "tech.manager@company.com",
                            FullName = "Tech Manager",
                            IsVectorIndexed = false,
                            JoiningDate = new DateTime(2012, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Bangalore",
                            PhoneNumber = "9876543216",
                            TeamId = 1,
                            UpdatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(500),
                            UserId = 7,
                            YearsOfExperience = 12m
                        });
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeProjects");
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.Property<int>("EmployeeSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YearsOfExperience")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("EmployeeSkillId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("LearningRecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecommendedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequirementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecommendationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("ResourceId");

                    b.ToTable("LearningRecommendations");
                });

            modelBuilder.Entity("LearningResource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ResourceTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("SkillId");

                    b.ToTable("LearningResources");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequirementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequirementId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ProjectSkill", b =>
                {
                    b.Property<int>("ProjectSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("YearsUsed")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("ProjectSkillId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("Requirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequirementId");

                    b.HasIndex("PostedById");

                    b.HasIndex("TeamId");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("RequirementSkill", b =>
                {
                    b.Property<int>("RequirementSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinYearsRequired")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequirementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weightage")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequirementSkillId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("SkillId");

                    b.ToTable("RequirementSkills");
                });

            modelBuilder.Entity("SearchHistory", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavedSearchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchedById")
                        .HasColumnType("INTEGER");

                    b.HasKey("SearchId");

                    b.HasIndex("SearchedById");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SkillId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Python programming language",
                            IsActive = true,
                            SkillName = "Python"
                        },
                        new
                        {
                            SkillId = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Java programming language",
                            IsActive = true,
                            SkillName = "Java"
                        },
                        new
                        {
                            SkillId = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "C# programming language",
                            IsActive = true,
                            SkillName = "C#"
                        },
                        new
                        {
                            SkillId = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "JavaScript programming language",
                            IsActive = true,
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            SkillId = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "TypeScript programming language",
                            IsActive = true,
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            SkillId = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Amazon Web Services",
                            IsActive = true,
                            SkillName = "AWS"
                        },
                        new
                        {
                            SkillId = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Microsoft Azure",
                            IsActive = true,
                            SkillName = "Azure"
                        },
                        new
                        {
                            SkillId = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Docker containerization",
                            IsActive = true,
                            SkillName = "Docker"
                        },
                        new
                        {
                            SkillId = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Kubernetes orchestration",
                            IsActive = true,
                            SkillName = "Kubernetes"
                        },
                        new
                        {
                            SkillId = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Jenkins CI/CD",
                            IsActive = true,
                            SkillName = "Jenkins"
                        },
                        new
                        {
                            SkillId = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "React.js library",
                            IsActive = true,
                            SkillName = "React"
                        },
                        new
                        {
                            SkillId = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Angular framework",
                            IsActive = true,
                            SkillName = "Angular"
                        },
                        new
                        {
                            SkillId = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(410),
                            Description = "Vue.js framework",
                            IsActive = true,
                            SkillName = "Vue.js"
                        },
                        new
                        {
                            SkillId = 14,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(420),
                            Description = "Node.js runtime",
                            IsActive = true,
                            SkillName = "Node.js"
                        },
                        new
                        {
                            SkillId = 15,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(420),
                            Description = "ASP.NET Core framework",
                            IsActive = true,
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(420),
                            Description = "Spring Boot framework",
                            IsActive = true,
                            SkillName = "Spring Boot"
                        },
                        new
                        {
                            SkillId = 17,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(420),
                            Description = "Microsoft SQL Server",
                            IsActive = true,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            SkillId = 18,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(420),
                            Description = "PostgreSQL database",
                            IsActive = true,
                            SkillName = "PostgreSQL"
                        },
                        new
                        {
                            SkillId = 19,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(420),
                            Description = "MongoDB NoSQL database",
                            IsActive = true,
                            SkillName = "MongoDB"
                        });
                });

            modelBuilder.Entity("SkillAlias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AliasId");

                    b.HasIndex("AliasName")
                        .IsUnique();

                    b.HasIndex("SkillId");

                    b.ToTable("SkillAliases");

                    b.HasData(
                        new
                        {
                            AliasId = 1,
                            AliasName = "K8s",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(430),
                            SkillId = 9
                        },
                        new
                        {
                            AliasId = 2,
                            AliasName = "K8",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 9
                        },
                        new
                        {
                            AliasId = 3,
                            AliasName = "JS",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 4
                        },
                        new
                        {
                            AliasId = 4,
                            AliasName = "TS",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 5
                        },
                        new
                        {
                            AliasId = 5,
                            AliasName = "React.js",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 11
                        },
                        new
                        {
                            AliasId = 6,
                            AliasName = "ReactJS",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 11
                        },
                        new
                        {
                            AliasId = 7,
                            AliasName = "NodeJS",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 14
                        },
                        new
                        {
                            AliasId = 8,
                            AliasName = "MSSQL",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 17
                        },
                        new
                        {
                            AliasId = 9,
                            AliasName = "MS SQL",
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(440),
                            SkillId = 17
                        });
                });

            modelBuilder.Entity("SkillCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.ToTable("SkillCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Programming Languages",
                            DisplayOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cloud & DevOps",
                            DisplayOrder = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Frontend Technologies",
                            DisplayOrder = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Backend Technologies",
                            DisplayOrder = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Databases",
                            DisplayOrder = 5
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Mobile Development",
                            DisplayOrder = 6
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Data Science & AI",
                            DisplayOrder = 7
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Testing & QA",
                            DisplayOrder = 8
                        });
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Department = "Technology",
                            IsActive = true,
                            Location = "Bangalore",
                            TeamName = "Engineering"
                        },
                        new
                        {
                            TeamId = 2,
                            Department = "Product Management",
                            IsActive = true,
                            Location = "Chennai",
                            TeamName = "Product"
                        },
                        new
                        {
                            TeamId = 3,
                            Department = "Technology",
                            IsActive = true,
                            Location = "Bangalore",
                            TeamName = "DevOps"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(450),
                            Email = "arun.kumar@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword1",
                            Role = "Employee"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(450),
                            Email = "beena.singh@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword2",
                            Role = "Employee"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(460),
                            Email = "rajesh.nair@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword3",
                            Role = "Employee"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(460),
                            Email = "priya.sharma@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword4",
                            Role = "Employee"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(460),
                            Email = "vikram.reddy@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword5",
                            Role = "Employee"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(460),
                            Email = "hr.manager@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword6",
                            Role = "HR"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedDate = new DateTime(2025, 12, 12, 12, 30, 10, 92, DateTimeKind.Utc).AddTicks(460),
                            Email = "tech.manager@company.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword7",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("Application", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("Applications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Requirement", "Requirement")
                        .WithMany("Applications")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasOne("Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LearningRecommendation", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("LearningRecommendations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Requirement", "Requirement")
                        .WithMany("LearningRecommendations")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LearningResource", "Resource")
                        .WithMany("LearningRecommendations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Requirement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("LearningResource", b =>
                {
                    b.HasOne("Skill", "Skill")
                        .WithMany("LearningResources")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Requirement", "Requirement")
                        .WithMany("Notifications")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("ProjectSkill", b =>
                {
                    b.HasOne("EmployeeProject", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Requirement", b =>
                {
                    b.HasOne("Employee", "PostedBy")
                        .WithMany("PostedRequirements")
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team", "Team")
                        .WithMany("Requirements")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PostedBy");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RequirementSkill", b =>
                {
                    b.HasOne("Requirement", "Requirement")
                        .WithMany("RequirementSkills")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill", "Skill")
                        .WithMany("RequirementSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requirement");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SearchHistory", b =>
                {
                    b.HasOne("Employee", "SearchedBy")
                        .WithMany("SearchHistories")
                        .HasForeignKey("SearchedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchedBy");
                });

            modelBuilder.Entity("Skill", b =>
                {
                    b.HasOne("SkillCategory", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillAlias", b =>
                {
                    b.HasOne("Skill", "Skill")
                        .WithMany("SkillAliases")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.HasOne("Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("EmployeeProjects");

                    b.Navigation("EmployeeSkills");

                    b.Navigation("LearningRecommendations");

                    b.Navigation("Notifications");

                    b.Navigation("PostedRequirements");

                    b.Navigation("SearchHistories");
                });

            modelBuilder.Entity("EmployeeProject", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("LearningResource", b =>
                {
                    b.Navigation("LearningRecommendations");
                });

            modelBuilder.Entity("Requirement", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("LearningRecommendations");

                    b.Navigation("Notifications");

                    b.Navigation("RequirementSkills");
                });

            modelBuilder.Entity("Skill", b =>
                {
                    b.Navigation("EmployeeSkills");

                    b.Navigation("LearningResources");

                    b.Navigation("ProjectSkills");

                    b.Navigation("RequirementSkills");

                    b.Navigation("SkillAliases");
                });

            modelBuilder.Entity("SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
